CREATE TABLE IF NOT EXISTS PERSON.USER_ACCOUNT (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(200) NOT NULL,
    role ENUM('ADMIN','TUTOR','PARTICIPANT') NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PERSON.PERSON (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    age TINYINT UNSIGNED,
    CONSTRAINT fk_person_user FOREIGN KEY (user_id) REFERENCES PERSON.USER_ACCOUNT(id)
);

